name: Build Kernel SM-T285

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: 'cm-14.1'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Cài đặt GCC phiên bản cũ hơn để tương thích với Kernel 3.10
          sudo apt-get install -y gcc-arm-linux-gnueabi gcc-6-arm-linux-gnueabi

      - name: Build Kernel
        run: |
          export ARCH=arm
          # Sử dụng gcc-6 thay vì phiên bản mặc định
          export CROSS_COMPILE=arm-linux-gnueabi-
          export CC=arm-linux-gnueabi-gcc-6
          
          make gtexswifi-dt_defconfig
          make -j$(nproc) KCFLAGS="-w" DISABLE_WERROR=1
          
      - name: Save Kernel Result
        uses: actions/upload-artifact@v4
        with:
          name: kernel-output
          path: arch/arm/boot/zImage*
