name: Build Kernel SM-T285

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: 'cm-14.1'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi bison flex libssl-dev bc

      - name: Build Kernel
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          export KCFLAGS="-w -DCONFIG_ARCH_SPR -DCONFIG_ARCH_GTEXSWIFI"
          export HOSTCFLAGS="-w -DCONFIG_ARCH_SPR"
          sed -i '/error "Unknown architecture specification"/d' include/soc/sprd/hardware.h
          make gtexswifi-dt_defconfig
          make -j$(nproc) zImage
          make -j$(nproc) dtbs
          
      - name: Prepare Output
        run: |
          mkdir -p output
          cp arch/arm/boot/zImage output/
          find arch/arm/boot/ -name "*.dtb" -exec cp {} output/ \;
          
      - name: Save Kernel Result
        uses: actions/upload-artifact@v4
        with:
          name: kernel-output
          path: output/*
